// <auto-generated />
using System;
using LV.SignFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LV.SignFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Documents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnvelopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FinalBlobPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FinalHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OriginalBlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginalHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeId", "Order");

                    b.ToTable("EnvelopeDocuments", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Envelope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SourceTemplateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SourceTemplateVersionId");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("Envelopes", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComparisonValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EnvelopeRoutingRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceEnvelopeFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeRoutingRuleId");

                    b.HasIndex("SourceEnvelopeFieldId");

                    b.ToTable("EnvelopeRoutingConditions", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvelopeRoutingRuleSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MatchType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetRecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TargetRecipientId");

                    b.HasIndex("EnvelopeRoutingRuleSetId", "Priority")
                        .IsUnique();

                    b.ToTable("EnvelopeRoutingRules", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvelopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeId");

                    b.ToTable("EnvelopeRoutingRuleSets", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Events", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvelopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("UserId");

                    b.HasIndex("EnvelopeId", "OccurredAt");

                    b.ToTable("EvelopeEvents", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Fields", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnvelopeDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvelopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvelopeRecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("Width")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("X")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Y")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeDocumentId");

                    b.HasIndex("EnvelopeId");

                    b.HasIndex("EnvelopeRecipientId");

                    b.ToTable("EnvelopeFields", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Recipients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSenderChangeRoutingOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSenderDeleteRecipient")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSenderEditRecipient")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("DeclinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("EnvelopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RecipientType")
                        .HasColumnType("int");

                    b.Property<int>("RoutingOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ViewedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeId");

                    b.HasIndex("UserId");

                    b.HasIndex("EnvelopeId", "RoutingOrder");

                    b.ToTable("EnvelopeRecipients", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvelopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("EnvelopeId", "ChangedAt");

                    b.ToTable("EnvelopeStatusHistories", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Organizations.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] is not null");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Signing.Signature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1 AND [IsActive] = 1");

                    b.ToTable("Signatures", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Signing.Stamps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name");

                    b.ToTable("Stamps", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OrganizationId", "Name");

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemplateVersionId", "Order");

                    b.ToTable("TemplateDocuments", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipientRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Width")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("X")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Y")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientRoleId");

                    b.HasIndex("TemplateDocumentId");

                    b.ToTable("TemplateFields", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRecipientRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSenderChangeRoutingOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSenderDeleteRecipient")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSenderEditRecipient")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DefaultUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RecipientType")
                        .HasColumnType("int");

                    b.Property<int>("RoutingOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DefaultUserId");

                    b.HasIndex("TemplateVersionId", "RoutingOrder");

                    b.ToTable("TemplateRecipientRoles", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComparisonValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceTemplateFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateRoutingRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceTemplateFieldId");

                    b.HasIndex("TemplateRoutingRuleId");

                    b.ToTable("TemplateRoutingConditions", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MatchType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetRecipientRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateRoutingRuleSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TargetRecipientRoleId");

                    b.HasIndex("TemplateRoutingRuleSetId", "Priority")
                        .IsUnique();

                    b.ToTable("TemplateRoutingRules", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TemplateVersionId");

                    b.ToTable("TemplateRoutingRuleSets", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SharedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SharedWithDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SharedWithUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SharedByUserId");

                    b.HasIndex("SharedWithDepartmentId");

                    b.HasIndex("SharedWithUserId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateShares", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemplateShares_ExactlyOneTarget", "(\r\n                    ([SharedWithUserId] IS NOT NULL AND [SharedWithDepartmentId] IS NULL)\r\n                    OR\r\n                    ([SharedWithUserId] IS NULL AND [SharedWithDepartmentId] IS NOT NULL)\r\n                  )");
                        });
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("TemplateVersions", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.PermissionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemProfile")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionProfiles", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.PermissionProfilePermission", b =>
                {
                    b.Property<Guid>("PermissionProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionProfileId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("PermissionProfilePermissions", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalIdentityId")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalIdentityId")
                        .IsUnique()
                        .HasFilter("[ExtenalIdentityId] is not null");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.UserPermissionProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "PermissionProfileId");

                    b.HasIndex("PermissionProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissionProfiles", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Documents", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Envelope", "Envelope")
                        .WithMany("Documents")
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envelope");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Envelope", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", "CreatedByUser")
                        .WithMany("CreatedEnvelopes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany("Envelopes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateVersion", "SourceTemplateVersion")
                        .WithMany("SourceEnvelopes")
                        .HasForeignKey("SourceTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");

                    b.Navigation("SourceTemplateVersion");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingCondition", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRule", "EnvelopeRoutingRule")
                        .WithMany("Conditions")
                        .HasForeignKey("EnvelopeRoutingRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Fields", "SourceEnvelopeField")
                        .WithMany("EnvelopeRoutingConditions")
                        .HasForeignKey("SourceEnvelopeFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnvelopeRoutingRule");

                    b.Navigation("SourceEnvelopeField");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRule", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRuleSet", "EnvelopeRoutingRuleSet")
                        .WithMany("Rules")
                        .HasForeignKey("EnvelopeRoutingRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Recipients", "TargetRecipient")
                        .WithMany("Rules")
                        .HasForeignKey("TargetRecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnvelopeRoutingRuleSet");

                    b.Navigation("TargetRecipient");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRuleSet", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Envelope", "Envelope")
                        .WithMany("EnvelopeRoutingRuleSets")
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envelope");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Events", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Envelope", "Envelope")
                        .WithMany("Events")
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Recipients", "Recipient")
                        .WithMany("Events")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Envelope");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Fields", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Documents", "EnvelopeDocument")
                        .WithMany("EnvelopeFields")
                        .HasForeignKey("EnvelopeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Envelope", "Envelope")
                        .WithMany("Fields")
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Recipients", "EnvelopeRecipient")
                        .WithMany("Fields")
                        .HasForeignKey("EnvelopeRecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Envelope");

                    b.Navigation("EnvelopeDocument");

                    b.Navigation("EnvelopeRecipient");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Recipients", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Envelope", "Envelope")
                        .WithMany("Recipients")
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Envelope");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.StatusHistory", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LV.SignFlow.Domain.Entities.Envelopes.Envelope", "Envelope")
                        .WithMany("StatusHistory")
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envelope");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Organizations.Department", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Signing.Signature", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", "User")
                        .WithMany("Signatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Signing.Stamps", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", "CreatedByUser")
                        .WithMany("Stamps")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.Template", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany("Templates")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", "OwnerUser")
                        .WithMany("Templates")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateDocument", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateVersion", "TemplateVersion")
                        .WithMany("Documents")
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateField", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateRecipientRole", "RecipientRole")
                        .WithMany("TemplateFields")
                        .HasForeignKey("RecipientRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateDocument", "TemplateDocument")
                        .WithMany("TemplateFields")
                        .HasForeignKey("TemplateDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientRole");

                    b.Navigation("TemplateDocument");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRecipientRole", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("DefaultUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateVersion", "TemplateVersion")
                        .WithMany("RecipientsRoles")
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingCondition", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateField", "SourceTemplateField")
                        .WithMany("TemplateRoutingConditions")
                        .HasForeignKey("SourceTemplateFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRule", "TemplateRoutingRule")
                        .WithMany("Conditions")
                        .HasForeignKey("TemplateRoutingRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceTemplateField");

                    b.Navigation("TemplateRoutingRule");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRule", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateRecipientRole", "TargetRecipientRole")
                        .WithMany("Rules")
                        .HasForeignKey("TargetRecipientRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRuleSet", "TemplateRoutingRuleSet")
                        .WithMany("Rules")
                        .HasForeignKey("TemplateRoutingRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetRecipientRole");

                    b.Navigation("TemplateRoutingRuleSet");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRuleSet", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.TemplateVersion", "TemplateVersion")
                        .WithMany("RoutingRuleSets")
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateShare", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Organizations.Department", null)
                        .WithMany()
                        .HasForeignKey("SharedWithDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.Template", "Template")
                        .WithMany("Shares")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateVersion", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Templates.Template", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.PermissionProfilePermission", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.Permission", "Permission")
                        .WithMany("PermissionProfilePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.PermissionProfile", "PermissionProfile")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionProfile");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.RolePermission", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Organizations.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LV.SignFlow.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.UserPermissionProfile", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.PermissionProfile", "PermissionProfile")
                        .WithMany("Users")
                        .HasForeignKey("PermissionProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", "User")
                        .WithMany("PermissionProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.UserRole", b =>
                {
                    b.HasOne("LV.SignFlow.Domain.Entities.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LV.SignFlow.Domain.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Documents", b =>
                {
                    b.Navigation("EnvelopeFields");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Envelope", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("EnvelopeRoutingRuleSets");

                    b.Navigation("Events");

                    b.Navigation("Fields");

                    b.Navigation("Recipients");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.EnvelopeRoutingRuleSet", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Fields", b =>
                {
                    b.Navigation("EnvelopeRoutingConditions");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Envelopes.Recipients", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Fields");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Organizations.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Envelopes");

                    b.Navigation("Templates");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.Template", b =>
                {
                    b.Navigation("Shares");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateDocument", b =>
                {
                    b.Navigation("TemplateFields");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateField", b =>
                {
                    b.Navigation("TemplateRoutingConditions");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRecipientRole", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("TemplateFields");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateRoutingRuleSet", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Templates.TemplateVersion", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("RecipientsRoles");

                    b.Navigation("RoutingRuleSets");

                    b.Navigation("SourceEnvelopes");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.Permission", b =>
                {
                    b.Navigation("PermissionProfilePermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.PermissionProfile", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LV.SignFlow.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedEnvelopes");

                    b.Navigation("PermissionProfiles");

                    b.Navigation("Signatures");

                    b.Navigation("Stamps");

                    b.Navigation("Templates");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
